services:
  - type: web
    name: punyo-market-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --no-input
    healthCheckPath: /
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --log-level debug --access-logfile - --timeout 120
    envVars:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.12.3
